nginx-buildpack/nginx_buildpack-cflinuxfs4-v1.2.34.zip:
  size: 8862812
  object_id: 41e4490a-da12-42c9-4c1e-9eb202517349
  sha: sha256:66c4fc5aab55fe7b70139a67b83f0672badb1864ef26cbebc8836b7291ec60bb
