nginx-buildpack/nginx_buildpack-cflinuxfs4-v1.2.32.zip:
  size: 9000447
  object_id: 8903cc36-8d5a-4e05-64d4-98cad7130f5d
  sha: sha256:b316a5484423320c0869cd11b275a2ee0975fc2b16b01fa0478c79ce911bb98e
